
DROP TABLE IF EXISTS FriendRequest;
DROP TABLE IF EXISTS Friend;

DROP TABLE IF EXISTS gName;
DROP TABLE IF EXISTS WorkAddress;

DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS DoctorSpecialization;

DROP TABLE IF EXISTS Doctor;
DROP TABLE IF EXISTS Patient;
DROP TABLE IF EXISTS gUser;

DROP VIEW IF EXISTS FullPatientView;
DROP VIEW IF EXISTS ReviewedDoctors;
DROP VIEW IF EXISTS DoctorReviewsMetaData;
DROP VIEW IF EXISTS FullDoctorView;